name: docs

on: [push, pull_request]

permissions:
  contents: read

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    permisions:
      contents: write # for Git to git push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install dependencies
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install package
        run: |
          pip install ".[docs]"

      # Build the book
      - name: Build the book
        run: |
          jupyter-book build docs

      # Push the book's HTML to github-pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
